
```{r}
library("psychotree")

data("SPISA", package = "psychotree")

write.table(SPISA,file="spisa.csv",sep=",",quote=TRUE,row.names=FALSE) 

```

#mydata
```{r}
library(readxl)
mydata <- read.csv("C:/Users/emily/OneDrive - University of Iowa/Spring2021/PSQF7375/FinalProject_DIF_ML/mydata.csv")

head(mydata)
names(mydata)
dim(mydata)
#View(mydata)
```

```{r}
mydata$resp <- as.matrix(mydata[ , 1:5]) #first five items response for spisa 1-5
head(mydata$resp)
```
```{r}
mydata$resp <- as.matrix(mydata[ , 6:10]) #first five items response for spisa 1-5
head(mydata$resp)
```

```{r}
mydata <- mydata[ , -(1:5)]
mydata
```

```{r}
mydata$resp <- as.matrix(mydata[ , 1:5]) #first five items response
mydata <- mydata[ , -(1:5)]
mydata <- subset(mydata, rowMeans(resp, na.rm = TRUE) > 0 &
+ rowMeans(resp, na.rm = TRUE) < 1)
```

```{r}
my_first_raschtree <- raschtree(spisa ~ age + gender +
+ semester + elite + spon, data = SPISA)
```

```{r}
plot(my_first_raschtree)
```

```{r}
library("colorspace")
plot(my_first_raschtree, col = rep(rainbow_hcl(5, c = 65, l = 65), each = 9))
```
